In [1]:
import numpy as np
from pathlib import Path

In [2]:
load_path = Path.cwd()/"Ex10_1.csv"
data = np.genfromtxt(
    load_path,
    delimiter=",",
    dtype=str,
    encoding="utf-8",
    skip_header=1,
)

data

array([['Alice', '80', '90', '85'],
       ['Bob', '70', '75', '80'],
       ['Charlie', '88', '92', '86'],
       ['David', '60', '65', '70'],
       ['Eva', '95', '88', '94']], dtype='<U7')

In [3]:
names = data[:, 0]
scores = data[:, 1:4].astype(float)

names, scores

(array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'], dtype='<U7'),
 array([[80., 90., 85.],
        [70., 75., 80.],
        [88., 92., 86.],
        [60., 65., 70.],
        [95., 88., 94.]]))

In [4]:
totals = scores.sum(axis=1)
avgs = scores.mean(axis=1)
totals, avgs

(array([255., 225., 266., 195., 277.]),
 array([85.        , 75.        , 88.66666667, 65.        , 92.33333333]))

In [5]:
# 先取得由大到小的排序索引
order = np.argsort(-totals)

# 建立一個空陣列存放排名
ranks = np.empty_like(order)
ranks[order] = np.arange(1, len(totals)+1)
ranks

array([3, 4, 2, 5, 1])

In [6]:
result = np.column_stack((names, totals, avgs, ranks))
result

array([['Alice', '255.0', '85.0', '3'],
       ['Bob', '225.0', '75.0', '4'],
       ['Charlie', '266.0', '88.66666666666667', '2'],
       ['David', '195.0', '65.0', '5'],
       ['Eva', '277.0', '92.33333333333333', '1']], dtype='<U32')

In [10]:
save_path = Path.cwd()/"Ex10_4_result.csv"
header = "姓名,總分,平均,排名"
np.savetxt(
    save_path,
    result,
    delimiter=",",
    fmt="%s",
    header=header,
    comments="",
    encoding="utf-8"
)
print(f"檔案已儲存至 {save_path}")

檔案已儲存至 c:\Users\TMP-214\pyExercise\0425_NumPy\Ex10_4_result.csv
